# Generated by Django 4.0.2 on 2022-03-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer'), ('ADMIN', 'Administrator')], default='CUSTOMER', max_length=15),
        ),
    ]
